import type {Metadata} from "next";
import "./globals.css";
import {Roboto_Condensed} from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"

const roboto_condensed = Roboto_Condensed({subsets: ['vietnamese', "latin"]})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${roboto_condensed.className} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
