import type {Metadata} from "next"
import "./globals.css"
import {Roboto_Condensed, Playfair_Display} from "next/font/google"
import {ThemeProvider} from "@/components/theme-provider"
import Header from "@/components/header"

const roboto_condensed = Roboto_Condensed({
    subsets: ["latin"],
    display: 'swap',
    variable: '--font-roboto',
})
const playfair = Playfair_Display({
    subsets: ["latin"],
    display: 'swap',
    variable: '--font-playfair-display',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${roboto_condensed.className} ${playfair.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
        >
            <Header/>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
