import type {Metadata} from "next";
import "./globals.css";
import {Roboto_Condensed} from "next/font/google";

const roboto_condensed = Roboto_Condensed({subsets: ['vietnamese', "latin"]})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${roboto_condensed.className} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
